# Generated by Django 4.0.3 on 2022-03-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0001_initial'),
        ('cars', '0003_alter_carmodel_brand_alter_carmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='auto_park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autopark.autoparkmodel'),
            preserve_default=False,
        ),
    ]
